#ifndef KWR_HEADER_KWRLEGOCOLORS_H
#define KWR_HEADER_KWRLEGOCOLORS_H

#include "sdl.h"

namespace kwr {

struct LegoColors {
    static SDL_Color White;
    static SDL_Color Grey;
    static SDL_Color Light_Yellow;
    static SDL_Color Brick_Red;
    static SDL_Color Brick_Yellow;
    static SDL_Color Light_Green;
    static SDL_Color Orange;
    static SDL_Color Light_Reddish_Violet;
    static SDL_Color Pastel_Blue;
    static SDL_Color Light_Orange_Brown;
    static SDL_Color Red_Orange;
    static SDL_Color Lemon;
    static SDL_Color Nougat;
    static SDL_Color Light_Brown;
    static SDL_Color Bright_Red;
    static SDL_Color Medium_Reddish_Violet;
    static SDL_Color Bright_Blue;
    static SDL_Color Bright_Yellow;
    static SDL_Color Earth_Orange;
    static SDL_Color Black;
    static SDL_Color Dark_Grey;
    static SDL_Color Dark_Green;
    static SDL_Color Medium_Green;
    static SDL_Color Light_Yellowish_Orange;
    static SDL_Color Bright_Green;
    static SDL_Color Dark_Orange;
    static SDL_Color Light_Bluish_Violet;
    static SDL_Color Light_Blue;
    static SDL_Color Light_Red;
    static SDL_Color Medium_Red;
    static SDL_Color Medium_Blue;
    static SDL_Color Light_Grey;
    static SDL_Color Bright_Violet;
    static SDL_Color Bright_Yellowish_Orange;
    static SDL_Color Bright_Orange;
    static SDL_Color Bright_Bluish_Green;
    static SDL_Color Earth_Yellow;
    static SDL_Color Bright_Bluish_Violet;
    static SDL_Color Medium_Bluish_Violet;
    static SDL_Color Medium_Yellowish_Green;
    static SDL_Color Medium_Bluish_Green;
    static SDL_Color Light_Bluish_Green;
    static SDL_Color Bright_Yellowish_Green;
    static SDL_Color Light_Yellowish_Green;
    static SDL_Color Medium_Yellowish_Orange;
    static SDL_Color Bright_Reddish_Orange;
    static SDL_Color Bright_Reddish_Violet;
    static SDL_Color Light_Orange;
    static SDL_Color Dark_Nougat;
    static SDL_Color Neon_Orange;
    static SDL_Color Neon_Green;
    static SDL_Color Sand_Blue;
    static SDL_Color Sand_Violet;
    static SDL_Color Medium_Orange;
    static SDL_Color Sand_Yellow;
    static SDL_Color Earth_Blue;
    static SDL_Color Earth_Green;
    static SDL_Color Dark_Army_Green;
    static SDL_Color Sand_Green;
    static SDL_Color Sand_Red;
    static SDL_Color New_Dark_Red;
    static SDL_Color Curry;
    static SDL_Color Fire_Yellow;
    static SDL_Color Flame_Yellowish_Orange;
    static SDL_Color Reddish_Brown;
    static SDL_Color Flame_Reddish_Orange;
    static SDL_Color Medium_Stone_Grey;
    static SDL_Color Royal_Blue;
    static SDL_Color Dark_Royal_Blue;
    static SDL_Color Bright_Reddish_Lilac;
    static SDL_Color Dark_Stone_Grey;
    static SDL_Color Light_Stone_Grey;
    static SDL_Color Dark_Curry;
    static SDL_Color Faded_Green;
    static SDL_Color Turquoise;
    static SDL_Color Light_Royal_Blue;
    static SDL_Color Medium_Royal_Blue;
    static SDL_Color Rust;
    static SDL_Color Brown;
    static SDL_Color Reddish_Lilac;
    static SDL_Color Lilac;
    static SDL_Color Light_Lilac;
    static SDL_Color Bright_Purple;
    static SDL_Color Light_Purple;
    static SDL_Color Light_Pink;
    static SDL_Color Light_Brick_Yellow;
    static SDL_Color Warm_Yellowish_Orange;
    static SDL_Color Cool_Yellow;
    static SDL_Color Dove_Blue;
    static SDL_Color Medium_Lilac;
    static SDL_Color Tiny_Medium_Blue;
    static SDL_Color Light_Nougat;
    static SDL_Color Dark_Brown;
    static SDL_Color Medium_Azur;
    static SDL_Color Aqua;
    static SDL_Color Medium_Lavender;
    static SDL_Color Lavender;
    static SDL_Color Spring_Yellowish_Green;
    static SDL_Color Olive_Green;
};

} // kwr

#endif
